export const ipcChannels = {
  applicationGetMetadata: 'application:get-metadata',
  applicationSetDefaultPdfApp: 'application:set-default-pdf-app',
  applicationOpenPdfPaths: 'application:open-pdf-paths',
  applicationTakePendingPdfPaths: 'application:take-pending-pdf-paths',
  applicationSetCloseBlocked: 'application:set-close-blocked',
  applicationCloseRequested: 'application:close-requested',
  applicationRequestQuit: 'application:request-quit',
  applicationConfirmClose: 'application:confirm-close',
  applicationCancelClose: 'application:cancel-close',
  themeGetSnapshot: 'theme:get-snapshot',
  themeChanged: 'theme:changed',
  updatesGetStatus: 'updates:get-status',
  updatesSetFrequency: 'updates:set-frequency',
  updatesCheckNow: 'updates:check-now',
  updatesInstallDownloaded: 'updates:install-downloaded',
  updatesSetRestartBlocked: 'updates:set-restart-blocked',
  updatesOpenReleasePage: 'updates:open-release-page',
  updatesStatusChanged: 'updates:status-changed',
  dialogOpenPdf: 'dialog:open-pdf',
  dialogSavePdfAs: 'dialog:save-pdf-as',
  fileRead: 'file:read',
  fileWrite: 'file:write',
  pdfCreateBlankDocument: 'pdf:create-blank-document',
  pdfReleaseTemporaryDocument: 'pdf:release-temporary-document',
  pdfLoadDocument: 'pdf:load-document',
  pdfGetPageGeometry: 'pdf:get-page-geometry',
  pdfSaveDocument: 'pdf:save-document',
  renderCoreGetBackendConfig: 'render-core:get-backend-config',
  renderCoreGetBackendSelection: 'render-core:get-backend-selection',
  renderCoreGetCapabilities: 'render-core:get-capabilities',
  renderCoreGetDiagnostics: 'render-core:get-diagnostics',
  renderCoreOpenDocument: 'render-core:open-document',
  renderCoreGetPageInfo: 'render-core:get-page-info',
  renderCoreRenderPage: 'render-core:render-page',
  renderCoreReadSurface: 'render-core:read-surface',
  renderCoreReleaseSurface: 'render-core:release-surface',
  renderCoreCloseDocument: 'render-core:close-document',
  testResolveFixture: 'test:resolve-fixture',
  testGetWindowState: 'test:get-window-state',
  testSetWindowBounds: 'test:set-window-bounds',
} as const;

export type IpcChannel = (typeof ipcChannels)[keyof typeof ipcChannels];
