export const ipcChannels = {
  applicationGetMetadata: 'application:get-metadata',
  applicationSetDefaultPdfApp: 'application:set-default-pdf-app',
  applicationOpenPdfPaths: 'application:open-pdf-paths',
  applicationTakePendingPdfPaths: 'application:take-pending-pdf-paths',
  applicationSetCloseBlocked: 'application:set-close-blocked',
  applicationCloseRequested: 'application:close-requested',
  applicationRequestQuit: 'application:request-quit',
  applicationConfirmClose: 'application:confirm-close',
  applicationCancelClose: 'application:cancel-close',
  themeGetSnapshot: 'theme:get-snapshot',
  themeChanged: 'theme:changed',
  updatesGetStatus: 'updates:get-status',
  updatesSetFrequency: 'updates:set-frequency',
  updatesCheckNow: 'updates:check-now',
  updatesInstallDownloaded: 'updates:install-downloaded',
  updatesSetRestartBlocked: 'updates:set-restart-blocked',
  updatesOpenReleasePage: 'updates:open-release-page',
  updatesStatusChanged: 'updates:status-changed',
  dialogOpenPdf: 'dialog:open-pdf',
  dialogSavePdfAs: 'dialog:save-pdf-as',
  fileRead: 'file:read',
  pdfCreateBlankDocument: 'pdf:create-blank-document',
  pdfReleaseDocument: 'pdf:release-document',
  pdfLoadDocument: 'pdf:load-document',
  pdfGetPageGeometry: 'pdf:get-page-geometry',
  pdfSaveDocument: 'pdf:save-document',
  signingChooseIdentity: 'signing:choose-identity',
  signingApprove: 'signing:approve',
  testResolveFixture: 'test:resolve-fixture',
  testAuthorizePdfSource: 'test:authorize-pdf-source',
  testAuthorizePdfSaveTarget: 'test:authorize-pdf-save-target',
  testGetWindowState: 'test:get-window-state',
  testSetWindowBounds: 'test:set-window-bounds',
  testGetProcessMetrics: 'test:get-process-metrics',
} as const;

export type IpcChannel = (typeof ipcChannels)[keyof typeof ipcChannels];
